In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
def input_function():

  print("Type the number of Decision Variables")
  n = int(input())

  
  print("Input for G matrix")
  G = np.zeros((n,n))
    
  for i in range(n):
    for j in range(n):
      print(f'Type ({i},{j}) element')
      G[i][j] = int(input())

  print("\nInput for d")
  d = np.zeros(n)
    
  for i in range(n):
    print(f'Type ({i+1}) element')
    d[i] = int(input())

  print("\nInput for x0")
  x0 = np.zeros(n)
    
  for i in range(n):
    print(f'Type ({i+1}) element')
    x0[i] = int(input())
    
  print("\nType number of equality constraints")
  neq = int(input())

  if neq > 0:
    
    Aeq = np.zeros((neq,n))
    beq = np.zeros((neq,1))
    
    print("\nInput for Aeq matrix")
    for i in range(neq):
      for j in range(n):
        print(f'Type ({i},{j}) element')
        Aeq[i][j] = int(input())
        
    print("\nInput for beq matrix")
    for i in range(neq):
      print(f'Type ({i+1}) element')
      beq[i] = int(input())
        
  else:
    Aeq = None
    beq = None

  print("\nType number of inequality constraints")
  nineq = int(input())

  if nineq > 0:
    Aineq = np.zeros((nineq,n))
    bineq = np.zeros((nineq,1))
    
    print("\nInput for Aineq matrix")
    
    for i in range(nineq):
      for j in range(n):
        print(f'Type ({i},{j}) element')
        Aineq[i][j] = int(input())
        
    print("\nInput for bineq matrix")
    
    for i in range(nineq):
      print(f'Type ({i+1}) element')
      bineq[i] = int(input())
        
  else:
    Aineq = None
    bineq = None

    
  return G, d, Aeq, beq, Aineq, bineq, x0, n, neq, nineq

In [10]:
G, d, Aeq, beq, Aineq, bineq, x0, n, neq, nineq = input_function()
print("Printing User Input Values")
print("G ",G)
print("d ", d)
print("Aeq ", Aeq)
print("beq ", beq)
print("Aineq ", Aineq)
print("bineq ", bineq)
print("x0 ", x0)
print("n ",n)
print("neq ", neq)
print("nineq ", nineq)

Type the number of Decision Variables
3
Input for G matrix
Type (0,0) element
6
Type (0,1) element
2
Type (0,2) element
1
Type (1,0) element
2
Type (1,1) element
5
Type (1,2) element
2
Type (2,0) element
1
Type (2,1) element
2
Type (2,2) element
4

Input for d
Type (1) element
-8
Type (2) element
-3
Type (3) element
-3

Input for x0
Type (1) element
1
Type (2) element
-2
Type (3) element
2

Type number of equality constraints
0

Type number of inequality constraints
2

Input for Aineq matrix
Type (0,0) element
1
Type (0,1) element
0
Type (0,2) element
1
Type (1,0) element
0
Type (1,1) element
1
Type (1,2) element
1

Input for bineq matrix
Type (1) element
3
Type (2) element
0
Printing User Input Values
G  [[6. 2. 1.]
 [2. 5. 2.]
 [1. 2. 4.]]
d  [-8. -3. -3.]
Aeq  None
beq  None
Aineq  [[1. 0. 1.]
 [0. 1. 1.]]
bineq  [[3.]
 [0.]]
x0  [ 1. -2.  2.]
n  3
neq  0
nineq  2


In [11]:
def QP_activeset(G,d,Aeq,beq,Aineq,bineq,x0,n,neq,nineq):
    
    x = x0